### ISSUE TITLE
[Markdown] Unable to find the required services AddMarkdownPages()

### ISSUE THREAD

**Issue by wangkanai** [wangkanai/wangkanai#671]
```log
Unhandled exception. System.InvalidOperationException: Unable to find the required services. Please add all the required services by calling 'IServiceCollection.AddMarkdownPages' inside the call to 'ConfigureService(...)' in the application startup code.
   at Wangkanai.Check.ThrowIfNull[T](Object value, String message) in D:\Sources\Wangkanai\System\src\Check.cs:line 211
   at Microsoft.Extensions.DependencyInjection.MarkdownEndpointRouteBuilderExtensions.EnsureMarkdownPagesServices(IEndpointRouteBuilder endpoints) in D:\Sources\Wangkanai\Markdown\src\DependencyInjection\MarkdownEndpointRouteBuilderExtensions.cs:line 157
   at Microsoft.Extensions.DependencyInjection.MarkdownEndpointRouteBuilderExtensions.MapMarkdownPages(IEndpointRouteBuilder endpoints) in D:\Sources\Wangkanai\Markdown\src\DependencyInjection\MarkdownEndpointRouteBuilderExtensions.cs:line 23
   at Program.<Main>$(String[] args) in D:\Sources\Wangkanai\Web\src\Program.cs:line 36
```

**Comment by wangkanai** [comment]
```log
Unhandled exception. System.AggregateException: Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: Wangkanai.Markdown.Infrastructure.MarkdownActionEndpointDataSourceFactory Lifetime: Singleton ImplementationType: Wangkanai.Markdown.Infrastructure.MarkdownActionEndpointDataSourceFactory': Unable to resolve service for type 'Wangkanai.Markdown.Infrastructure.MarkdownActionEndpointDataSourceIdProvider' while attempting to activate 'Wangkanai.Markdown.Infrastructure.MarkdownActionEndpointDataSourceFactory'.)
 ---> System.InvalidOperationException: Error while validating the service descriptor 'ServiceType: Wangkanai.Markdown.Infrastructure.MarkdownActionEndpointDataSourceFactory Lifetime: Singleton ImplementationType: Wangkanai.Markdown.Infrastructure.MarkdownActionEndpointDataSourceFactory': Unable to resolve service for type 'Wangkanai.Markdown.Infrastructure.MarkdownActionEndpointDataSourceIdProvider' while attempting to activate 'Wangkanai.Markdown.Infrastructure.MarkdownActionEndpointDataSourceFactory'.
 ---> System.InvalidOperationException: Unable to resolve service for type 'Wangkanai.Markdown.Infrastructure.MarkdownActionEndpointDataSourceIdProvider' while attempting to activate 'Wangkanai.Markdown.Infrastructure.MarkdownActionEndpointDataSourceFactory'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain, Int32 slot)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(ServiceDescriptor serviceDescriptor, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.ValidateService(ServiceDescriptor descriptor)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.ValidateService(ServiceDescriptor descriptor)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(ICollection`1 serviceDescriptors, ServiceProviderOptions options)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(ICollection`1 serviceDescriptors, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(IServiceCollection services, ServiceProviderOptions options)
   at Microsoft.Extensions.Hosting.HostApplicationBuilder.Build()
   at Microsoft.AspNetCore.Builder.WebApplicationBuilder.Build()
   at Program.<Main>$(String[] args) in D:\Sources\Wangkanai\Web\src\Program.cs:line 14
```

This bug goes very deep, its not going to close that easily.

**Comment by wangkanai** [comment]
![image](https://github.com/wangkanai/wangkanai/assets/10666633/b456a2d3-c521-4d41-a4dd-a2c2bc424b5f)
